import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "rolex-gmt-master-ii-126710blro-2026",
    name: "GMT-Master II Unworn 2026 / 126710BLRO - New style box",
    brand: "Rolex",
    reference: "126710BLRO",
    price: 33940,
    image: "https://img.chrono24.com/images/uhren/40929462-kuk7jmj81v20ua65hhe2u7pk-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/40929462-kuk7jmj81v20ua65hhe2u7pk-Square420.jpg",
      "https://img.chrono24.com/images/uhren/40929462-o2cc2h92l0ge0epy3p6cyyra-Square420.jpg",
      "https://img.chrono24.com/images/uhren/40929462-im3sa28wf4eid1tusvxoyj4o-Square420.jpg",
      "https://img.chrono24.com/images/uhren/40929462-h1c88nt1p80f14tjut7l8uaz-Square420.jpg",
      "https://img.chrono24.com/images/uhren/40929462-lbspq1vw2pjuznm87dmn85bx-Square420.jpg",
      "https://img.chrono24.com/images/uhren/40929462-cfs0yasy8afh7hml0rkrxqne-Square420.jpg",
      "https://img.chrono24.com/images/uhren/40929462-i8ksnqeqtpvykptgz4fk16vi-Square420.jpg"
    ],
    description: "The Rolex GMT-Master II Ref. 126710BLRO, known worldwide as the \"Pepsi,\" is one of the most iconic and sought-after Rolex sports watches ever produced. Instantly recognizable by its signature red and blue Cerachrom bezel, this outstanding 2026 model combines Rolex's legendary travel-watch heritage with the latest advancements in precision and performance. Paired with the elegant Jubilee bracelet, it offers the perfect balance of sportiness, comfort, and timeless style.\n\nPowered by the Rolex Caliber 3285 automatic movement, the watch delivers exceptional accuracy, reliability, and an approximate 70-hour power reserve. The 40mm Oystersteel case is fitted with a scratch-resistant sapphire crystal featuring the signature Cyclops date magnifier and is water-resistant to 100 meters. Its bidirectional 24-hour bezel and independently adjustable local hour hand allow effortless tracking of multiple time zones, making it the ideal companion for international travel.\n\nThis watch is 100% unworn and comes as a complete full set, including the original Rolex box, international warranty card dated 2026, instruction booklets, green Rolex card holder, green COSC hangtag, and the original white serial tag, if supplied by Rolex. The bracelet has never been sized, and in accordance with Rolex policy, all factory protective stickers were removed by the Authorized Dealer prior to the original sale.\n\nThe watch is in stock and ready for immediate shipment.",
    category: "mens",
    condition: "like-new",
    year: 2026,
    features: [
      "Rolex Caliber 3285 automatic movement",
      "40mm Oystersteel case",
      "Red and blue Cerachrom 24-hour bezel (\"Pepsi\")",
      "Black dial",
      "Jubilee bracelet (never sized)",
      "Scratch-resistant sapphire crystal with Cyclops magnifier",
      "100m water resistance",
      "Approximately 70-hour power reserve",
      "GMT/second time zone function",
      "Date display",
      "Original Rolex box (new style)",
      "International warranty card dated 2026",
      "Complete full set with all documentation",
      "100% unworn condition",
      "In stock - ready for immediate shipment"
    ],
    inStock: true,
  },
  {
    id: "rolex-gmt-master-ii-16710",
    name: "GMT-Master II — PEPSI INSERT",
    brand: "Rolex",
    reference: "16710",
    price: 13000,
    image: "https://img.chrono24.com/images/uhren/47465251-iikab07fmolnubvkd0k6dvu5-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/47465251-iikab07fmolnubvkd0k6dvu5-Square420.jpg",
      "https://img.chrono24.com/images/uhren/47465251-9k203h0aejruehnyt05732ag-Square420.jpg",
      "https://img.chrono24.com/images/uhren/47465251-q6omhg7dyige5eimjlnnbiky-Square420.jpg",
      "https://img.chrono24.com/images/uhren/47465251-6s1xyrvwvw6bfiwgfp499yym-Square420.jpg",
      "https://img.chrono24.com/images/uhren/47465251-18cr2zhb4i8i0vrhiaijvqmk-Square420.jpg"
    ],
    description: "Offered for sale is this iconic Rolex GMT-Master II, reference 16710, featuring the legendary blue and red \"Pepsi\" bezel paired with a classic black dial. Renowned as one of the most collectible modern GMT-Master references, the 16710 combines timeless design, exceptional versatility, and true travel functionality with its independently adjustable 24-hour hand.\n\nPresented in very good pre-owned condition, this watch shows only light signs of careful wear and has been well maintained throughout its life. It is accompanied by its original Rolex warranty papers. The original box is not included. The exact year of production is unknown.\n\nIncluded: Original Rolex warranty papers, watch only, no original box.\n\nAuthenticity & Inspection: Every watch we offer is thoroughly inspected by our experienced team to verify authenticity, functionality, and overall condition prior to sale. We are committed to presenting our timepieces with transparency and accuracy so customers can make informed purchasing decisions. Please review all product photographs carefully, as they are an important part of the product description and show the watch's condition and included accessories. We are dedicated to providing an exceptional buying experience, with prompt communication, secure insured shipping, and professional service before and after purchase. Customers may contact us with questions or requests for additional photographs.\n\nReturn Policy: All watch sales are final.",
    category: "mens",
    condition: "very-good",
    features: [
      "Rolex Manufacture Automatic GMT Movement",
      "40mm case diameter",
      "Stainless Steel case material",
      "Blue & Red \"Pepsi\" 24-hour rotating bezel",
      "Black dial",
      "Rolex Oyster Bracelet in Stainless Steel",
      "Scratch-resistant sapphire crystal with Cyclops date magnifier",
      "100 meters / 330 feet water resistance",
      "Independently adjustable 24-hour hand",
      "Original Rolex warranty papers included",
      "Watch only - no original box",
      "Very good pre-owned condition",
      "Thoroughly inspected for authenticity and functionality"
    ],
    inStock: true,
  },
  {
    id: "rolex-gmt-master-ii-126719blro-superman-2024",
    name: "GMT-Master II Like New 2024 Superman | Full Set | Meteorite White Gold",
    brand: "Rolex",
    reference: "126719BLRO",
    price: 79500,
    image: "https://img.chrono24.com/images/uhren/0bxfux80zkae-m6yxn13qzfqbk170h30oqq84-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/0bxfux80zkae-m6yxn13qzfqbk170h30oqq84-Square420.jpg",
      "https://img.chrono24.com/images/uhren/39ll8neix0po-l5hfjglwqin8l3b6ea4oolt0-Square420.jpg",
      "https://img.chrono24.com/images/uhren/z6tjfwvsaw2i-zligdr2wz2spvvyma04qffuk-Square420.jpg",
      "https://img.chrono24.com/images/uhren/45oh7wbbgh6o-ars60y7ep5w6tsvshr66plao-Square420.jpg",
      "https://img.chrono24.com/images/uhren/7fdxijpvgp05-0op5higccke07xm3fcke8uer-Square420.jpg",
      "https://img.chrono24.com/images/uhren/fgsewmau8wzr-82c2cugzu9pgmnyembc3hocu-Square420.jpg",
      "https://img.chrono24.com/images/uhren/6c706hw4dxys-njieo6jjpasoojhr5gzv45cp-ExtraLarge.jpg",
      "https://img.chrono24.com/images/uhren/2cy6jokm9dqs-wmfy31museo8ldowyw45mwas-ExtraLarge.jpg"
    ],
    description: "Like New 2024 Rolex GMT-Master II Superman 126719BLRO\n\nWhite Gold Case and Bracelet.\n\nFactory Meteorite Dial.\n\nBLRO Pepsi Ceramic Bezel.\n\nBezel Protector included.\n\nFull Links included.\n\nFull Set.\n\nComes complete with box, papers, green and white tags.",
    category: "mens",
    condition: "like-new",
    year: 2024,
    features: [
      "White Gold case material",
      "White Gold bracelet",
      "Factory Meteorite dial",
      "BLRO Pepsi Ceramic bezel",
      "Bezel protector included",
      "Full bracelet links included",
      "Original Rolex box",
      "Original papers",
      "Green and white tags",
      "Full set",
      "Like new & unworn condition",
      "2024 production year",
      "Excl. shipping"
    ],
    inStock: true,
  },
  {
    id: "rolex-gmt-master-6542-1956",
    name: "GMT-Master Pepsi 6542. 1956 year.",
    brand: "Rolex",
    reference: "6542",
    price: 15000,
    image: "https://img.chrono24.com/images/uhren/ppc58t7pmapt-f73hwn622pjh8j79hpfn7z1h-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/ppc58t7pmapt-f73hwn622pjh8j79hpfn7z1h-Square420.jpg",
      "https://img.chrono24.com/images/uhren/u3cm7eevox8y-6ztboxnpw7d3s447g060a5g1-Square420.jpg",
      "https://img.chrono24.com/images/uhren/9j0ei6rnqybh-ffznmzzlwhwqbl0ptm7i7igt-Square420.jpg",
      "https://img.chrono24.com/images/uhren/q5r87hy8wjee-e2yxwga4iptq74sqy2a5cpu1-Square420.jpg",
      "https://img.chrono24.com/images/uhren/gr48kuo4j570-39p7n3k4f1qikmlhywu4t2i5-Square420.jpg",
      "https://img.chrono24.com/images/uhren/w0bwlun6a6sf-n84cobz9izrn3i65qozctpmk-Square420.jpg",
      "https://img.chrono24.com/images/uhren/yqvxo0qssew1-s7xic4dc5yhkm3ugrl1b9cka-Square420.jpg",
      "https://img.chrono24.com/images/uhren/bn07yx817tqr-2oumbv1gl3mikwib95swinig-Square420.jpg",
      "https://img.chrono24.com/images/uhren/5x3bxob85lkc-fa36g019pmpj9kpljjxaji4z-ExtraLarge.jpg",
      "https://img.chrono24.com/images/uhren/ckk9gdrccxay-543nslszbwa08czrptx5qvpb-ExtraLarge.jpg"
    ],
    description: "1956 Rolex Pepsi 6542. Strap is aftermarket. Not original Bakelite bezel. Crown is Rolex replaced service. I just got the watch verified, cleaned and serviced by vintage Rolex expert John Buckley of Tuscany Rose Jewelers in New Jersey. Perfect collectors watch.",
    category: "mens",
    condition: "fair",
    year: 1956,
    features: [
      "Vintage 1956 GMT-Master reference 6542",
      "Aftermarket strap",
      "Not original Bakelite bezel",
      "Rolex replacement service crown",
      "Recently verified, cleaned and serviced",
      "Serviced by vintage Rolex expert John Buckley",
      "Tuscany Rose Jewelers, New Jersey",
      "Collector's watch",
      "No original box",
      "No original papers"
    ],
    inStock: true,
  },
  {
    id: "rolex-submariner-116610ln",
    name: "Submariner Date",
    brand: "Rolex",
    reference: "116610LN",
    price: 14500,
    image: "https://img.chrono24.com/images/uhren/46754029-5zupr72e2m9isig5aimd8eyc-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/46754029-5zupr72e2m9isig5aimd8eyc-Square420.jpg"
    ],
    description: "The iconic Rolex Submariner Date in stainless steel with black ceramic bezel. The reference 116610LN is the culmination of decades of dive watch evolution.",
    category: "mens",
    condition: "excellent",
    features: [
      "Oyster Perpetual automatic movement",
      "40mm case diameter",
      "Ceramic Cerachrom bezel",
      "300m water resistance",
      "Glidelock clasp extension",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "patek-nautilus-5711",
    name: "Nautilus",
    brand: "Patek Philippe",
    reference: "5711/1A-010",
    price: 89500,
    image: "https://img.chrono24.com/images/uhren/ja3uoqq4z873-pmgpjjzfng9tn67bl4ahjigt-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/ja3uoqq4z873-pmgpjjzfng9tn67bl4ahjigt-Square420.jpg"
    ],
    description: "The legendary Patek Philippe Nautilus in stainless steel. One of the most sought-after luxury sports watches in the world.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 26-330 S C",
      "40mm case diameter",
      "Blue dial with horizontal embossing",
      "120m water resistance",
      "Date display",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "ap-royaloak-15400st",
    name: "Royal Oak",
    brand: "Audemars Piguet",
    reference: "15400ST.OO.1220ST.03",
    price: 42500,
    image: "https://img.chrono24.com/images/uhren/47285184-ljofrp95e2g0fihxtsj2s9cg-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/47285184-ljofrp95e2g0fihxtsj2s9cg-Square420.jpg"
    ],
    description: "The Audemars Piguet Royal Oak in stainless steel with silver-toned 'Grande Tapisserie' dial. An icon of luxury sports watch design.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 3120",
      "41mm case diameter",
      "Grande Tapisserie dial",
      "50m water resistance",
      "Date display",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "omega-speedmaster-moonwatch",
    name: "Speedmaster Professional Moonwatch",
    brand: "Omega",
    reference: "311.30.42.30.01.005",
    price: 6200,
    image: "https://img.chrono24.com/images/uhren/yprit581nrhu-sw57167nmo0cnt91n299gjks-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/yprit581nrhu-sw57167nmo0cnt91n299gjks-Square420.jpg"
    ],
    description: "The legendary Omega Speedmaster Professional, the first watch worn on the moon. Hesalite crystal and manual-wound movement.",
    category: "mens",
    condition: "excellent",
    features: [
      "Manual-wound Caliber 1861",
      "42mm case diameter",
      "Hesalite crystal",
      "50m water resistance",
      "Tachymeter bezel",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "cartier-santos-wssa0009",
    name: "Santos de Cartier",
    brand: "Cartier",
    reference: "WSSA0009",
    price: 7100,
    image: "https://img.chrono24.com/images/uhren/47936706-xfy7uaub2uovxtblg2f3c9qw-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/47936706-xfy7uaub2uovxtblg2f3c9qw-Square420.jpg"
    ],
    description: "The Cartier Santos in stainless steel with iconic square case and blue hands. A timeless dress watch with aviation heritage.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 1847 MC",
      "39.8mm case diameter",
      "Sapphire crystal",
      "100m water resistance",
      "Date display",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "rolex-daytona-116500ln",
    name: "Cosmograph Daytona 'Panda'",
    brand: "Rolex",
    reference: "116500LN",
    price: 35800,
    image: "https://img.chrono24.com/images/uhren/46686500-3w2cya5lrkq1oaf82hqdujfn-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/46686500-3w2cya5lrkq1oaf82hqdujfn-Square420.jpg"
    ],
    description: "The Rolex Cosmograph Daytona with white dial and black sub-dials, known as the 'Panda' configuration. Ceramic bezel and Oystersteel case.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 4130",
      "40mm case diameter",
      "Ceramic Cerachrom bezel",
      "100m water resistance",
      "Chronograph function",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "patek-aquanaut-5167a",
    name: "Aquanaut",
    brand: "Patek Philippe",
    reference: "5167A-001",
    price: 42500,
    image: "https://img.chrono24.com/images/uhren/puihb2z75g66-e2q6qblmyqge91sbopq75j1m-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/puihb2z75g66-e2q6qblmyqge91sbopq75j1m-Square420.jpg"
    ],
    description: "The Patek Philippe Aquanaut in stainless steel with black embossed dial and tropical composite strap.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 26-330 S C",
      "40mm case diameter",
      "Black embossed dial",
      "120m water resistance",
      "Date display",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "omega-seamaster-300m",
    name: "Seamaster Diver 300M",
    brand: "Omega",
    reference: "210.30.42.20.01.001",
    price: 5400,
    image: "https://img.chrono24.com/images/uhren/47837583-jd8rrhd3e4s6rpwpv0ecx79k-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/47837583-jd8rrhd3e4s6rpwpv0ecx79k-Square420.jpg"
    ],
    description: "The Omega Seamaster Professional Diver 300M with black ceramic dial and wave pattern. Master Chronometer certified.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 8800",
      "42mm case diameter",
      "Ceramic dial with wave pattern",
      "300m water resistance",
      "Helium escape valve",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "iwc-portugieser-iw371605",
    name: "Portugieser Chronograph",
    brand: "IWC",
    reference: "IW371605",
    price: 8900,
    image: "https://img.chrono24.com/images/uhren/vyrsxawrzfg2-q4nomrjey7iurj3tey9g6n1n-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/vyrsxawrzfg2-q4nomrjey7iurj3tey9g6n1n-Square420.jpg"
    ],
    description: "The IWC Portugieser Chronograph with silver-plated dial and leaf-shaped hands. Classic dress chronograph design.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 79350",
      "41mm case diameter",
      "Silver-plated dial",
      "30m water resistance",
      "Chronograph function",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "rolex-gmt-master-ii-126710blnr",
    name: "GMT-Master II 'Batgirl'",
    brand: "Rolex",
    reference: "126710BLNR",
    price: 18900,
    image: "https://img.chrono24.com/images/uhren/jvyx4uddyxr5-euoy50xr3q8max0a70t2im9c-Square420.jpg",
    images: [
      "https://img.chrono24.com/images/uhren/jvyx4uddyxr5-euoy50xr3q8max0a70t2im9c-Square420.jpg"
    ],
    description: "The Rolex GMT-Master II with blue and black ceramic bezel, nicknamed 'Batgirl'. Jubilee bracelet and GMT function.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 3285",
      "40mm case diameter",
      "Ceramic Cerachrom bezel",
      "100m water resistance",
      "GMT function",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "cartier-tank-must-wsta0041",
    name: "Tank Must",
    brand: "Cartier",
    reference: "WSTA0041",
    price: 3200,
    image: "/generated/product-cartier-santos.png",
    images: ["/generated/product-cartier-santos.png"],
    description: "The Cartier Tank Must in stainless steel with silver-toned dial. A timeless rectangular dress watch with Roman numerals.",
    category: "mens",
    condition: "excellent",
    features: [
      "Quartz movement",
      "33.7mm x 25.5mm case",
      "Sapphire crystal",
      "30m water resistance",
      "Blue synthetic spinel cabochon",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "tudor-bb58-79030n",
    name: "Black Bay Fifty-Eight",
    brand: "Tudor",
    reference: "79030N",
    price: 3900,
    image: "/generated/product-rolex-sub.png",
    images: ["/generated/product-rolex-sub.png"],
    description: "The Tudor Black Bay Fifty-Eight with gilt details and black dial. Vintage-inspired dive watch with modern reliability.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber MT5402",
      "39mm case diameter",
      "Aluminum bezel insert",
      "200m water resistance",
      "Gilt details",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "ap-royaloak-chrono-26331st",
    name: "Royal Oak Chronograph",
    brand: "Audemars Piguet",
    reference: "26331ST.OO.1220ST.03",
    price: 54900,
    image: "/generated/product-ap-royaloak.png",
    images: ["/generated/product-ap-royaloak.png"],
    description: "The Audemars Piguet Royal Oak Chronograph with silver dial and integrated chronograph pushers.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 2385",
      "41mm case diameter",
      "Integrated chronograph",
      "50m water resistance",
      "Date display",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "omega-planet-ocean-215.30.44.21.01.001",
    name: "Seamaster Planet Ocean",
    brand: "Omega",
    reference: "215.30.44.21.01.001",
    price: 6700,
    image: "/generated/product-omega-speedmaster.png",
    images: ["/generated/product-omega-speedmaster.png"],
    description: "The Omega Seamaster Planet Ocean with black ceramic bezel and orange accents. Professional dive watch with Co-Axial movement.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 8500",
      "43.5mm case diameter",
      "Ceramic bezel",
      "600m water resistance",
      "Helium escape valve",
      "Box and papers"
    ],
    inStock: true,
  },
  {
    id: "rolex-datejust-36-126234",
    name: "Datejust 36",
    brand: "Rolex",
    reference: "126234",
    price: 11200,
    image: "/generated/product-rolex-daytona.png",
    images: ["/generated/product-rolex-daytona.png"],
    description: "The Rolex Datejust 36 with white dial and fluted bezel. Classic dress watch with timeless design.",
    category: "mens",
    condition: "excellent",
    features: [
      "Automatic Caliber 3235",
      "36mm case diameter",
      "Fluted bezel",
      "100m water resistance",
      "Date display with Cyclops",
      "Box and papers"
    ],
    inStock: true,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter(p => p.brand.toLowerCase() === brand.toLowerCase());
}